export const WPM_RATE = 3; // Words-per-second (WPS), not WPM. 3 WPS = 180 words per minute.

export const Elements = {
    scriptBody: document.getElementById('script-body'),
    btnAddRow: document.getElementById('btn-add-row'),
    btnSave: document.getElementById('btn-save'),
    btnPrint: document.getElementById('btn-print'),
    template: document.getElementById('row-template'),
    metaSlug: document.getElementById('meta-slug'),
    metaDepartment: document.getElementById('meta-department'),
    metaReporter: document.getElementById('meta-reporter'),
    metaStatus: document.getElementById('meta-status'),
    metaAnchor: document.getElementById('meta-anchor'),
    totalTimeDisplay: document.getElementById('total-time'),
    sidebar: document.getElementById('archive-sidebar'),
    btnArchive: document.getElementById('btn-archive') || document.getElementById('nav-find-story'),
    btnCloseArchive: document.getElementById('btn-close-archive'),
    searchDept: document.getElementById('search-department'),
    searchKw: document.getElementById('search-keyword'),
    btnDoSearch: document.getElementById('btn-do-search'),
    archiveResults: document.getElementById('archive-results'),
    modal: document.getElementById('preview-modal'),
    btnClosePreview: document.getElementById('btn-close-preview'),
    btnLoadPreview: document.getElementById('btn-load-preview'),
    btnCancelPreview: document.getElementById('btn-cancel-preview'),
    previewTitle: document.getElementById('preview-title'),
    previewBody: document.getElementById('preview-body'),
    cmdMenu: document.getElementById('cmd-autocomplete'),
    newBtnEl: document.getElementById('btn-new') || document.getElementById('nav-new-story'),
    navMyStory: document.getElementById('nav-my-story'),
    mystorySidebar: document.getElementById('mystory-sidebar'),
    btnCloseMystory: document.getElementById('btn-close-mystory'),
    tabMyStory: document.getElementById('tab-my-story'),
    tabMyBin: document.getElementById('tab-my-bin'),
    mystoryResults: document.getElementById('mystory-results'),
};

export const State = {
    currentStoryId: null,
    previewingStoryId: null,
    isAutoSaving: false,
    autoSaveInterval: null,
    acTarget: null,
    acCursorPos: -1,
    acSelectedIndex: 0,
    storyKeywords: '',
    initialStatus: null,
    isReadOnly: false,
    lockInterval: null,
    isSaving: false
};
